# -*- coding: utf-8 -*-
"""Sepsis Optimisé.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o3jl7Qk82FBen5amVeiUI7pTpa8xprBi
"""

pip install pycaret

# Import des librairies
import pycaret
from pycaret.classification import *
import pandas as pd
import pickle

# Chargez les données dans un dataframe pandas:
df = pd.read_csv('/content/data_sepsis.csv')

# Voici les données manquantes
df.isnull().sum()

# Travailler la variable catégorielle "Sepsis", convert into INT
df['Sepssis'] = df['Sepssis'].apply(lambda x: 1 if x == 'Positive' else 0)

# Supprimer la variable "ID"
df = df.drop('ID', axis=1)

# Configurez l'environnement PyCaret
clf1 = setup(data = df, target = 'Sepssis', session_id=42, normalize=False,
             transformation=True, remove_multicollinearity=True, multicollinearity_threshold=0.95)

# Comparez les modèles et sélectionnez le meilleur
best = compare_models()

# Faites des prédictions sur l'ensemble de test:
y_pred = predict_model(best)

# Finalisez le modèle
final_model = finalize_model(best)

# Affichez les métriques du modèle
print(y_pred)

# Sauvegarde du modèle
pickle.dump(final_model, open('model.pkl', 'wb'))

#Analyse du modèle

# plot confusion matrix
plot_model(best, plot = 'confusion_matrix')
# plot AUC
plot_model(best, plot = 'auc')
# plot feature importance
plot_model(best, plot = 'feature')